amazon/urls.py
from django.urls import path
from . import views
from django.contrib import admin
from django.contrib.auth import views as django_auth_views

app_name = 'amazon'

urlpatterns = [
    path('lp/', views.Lp.as_view(), name='lp'),
    path('items/', views.ItemList.as_view(), name = 'item_list'),
    path('item/<int:pk>', views.ItemDetail.as_view(), name = 'item_detail'),
    path('', views.Login.as_view(), name = "login"),
    path('logout', django_auth_views.LogoutView.as_view(), name = "logout"),
    path('sign_up/', views.SignUp.as_view(), name='sign_up'), 
    path('sign_up/done/<token>', views.SignUpDone.as_view(), name='sign_up_done'),
]

myECsite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myECsite/amazon/', include('amazon.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

amazon/models.py
from django.db import models
from django import forms
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.core.mail import send_mail
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone

# Create your models here.
class Product(models.Model):
    class Meta:
        verbose_name = '商品'
        verbose_name_plural = "商品"

    thumbnail = models.ImageField(
        verbose_name = 'サムネイル',
        upload_to = "thumbnails/",
    )

    name = models.CharField(
        verbose_name = '名前',
        max_length=150,
        null = False,
        blank=False,
    )

    price = models.IntegerField(
        verbose_name = '価格',
    )

    description = models.TextField(
        verbose_name = '説明',
    )


class MyUserManager(BaseUserManager):

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('The given email must be set')

        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    class Meta:
        verbose_name = 'ユーザ'
        verbose_name_plural = 'ユーザ'

    email = models.EmailField('メールアドレス', max_length=150, null = False, blank=False, unique = True)
    name = models.CharField('名前', max_length=150, null = False, blank=False)
    
    is_staff = models.BooleanField(
        '管理者',
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        '有効',
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = MyUserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name',]

    def email_user(self, subject, message, from_email=None, **kwargs):
        send_mail(subject, message, from_email, [self.email], **kwargs)

    @property
    def username(self):
        return self.email

amazon/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from .models import *
from django.core.exceptions import ValidationError


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label  # placeholderにフィールドのラベルを入れる


class SignUpForm(UserCreationForm):
    """ユーザー登録用フォーム"""

    class Meta:
        model = User
        fields = ('email', 'name',)
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label
            

amazon/views.py
from django.shortcuts import render
from django.views import generic
from .models import *
from django.contrib.auth.views import LoginView
from .forms import *
from django.http import HttpResponseRedirect, JsonResponse, HttpResponseBadRequest #[6-4]追加
from django.core.signing import BadSignature, SignatureExpired, dumps, loads #[6-4]追加
from django.urls import reverse #[6-4]追加
from django.contrib.sites.shortcuts import get_current_site #[6-4]追加
from django.template.loader import get_template #[6-4]追加
from django.contrib import messages
from django.conf import settings

# Create your views here.

class Lp(generic.TemplateView):
    template_name = 'amazon/lp.html'


    def get_context_data(self, **kwargs):
        def get_context_data(self, **kwargs):
            context = super(Lp, self).get_context_data(**kwargs)
            all_items = Product.objects.all()
            context['items'] = all_items
            return context


class ItemList(generic.ListView):
    model = Product
    template_name = 'amazon/item_list.html'

    def get_queryset(self):
        products = Product.objects.all()
        if 'q' in self.request.GET and self.request.GET['q'] != None:
            q = self.request.GET['q']
            products = products.filter(name__icontains = q)
        return products


class ItemDetail(generic.DetailView):
    model = Product
    template_name = 'amazon/item_detail.html'


class Login(LoginView):
    form_class = LoginForm
    template_name = 'amazon/login.html'


class SignUp(generic.CreateView):
    """ユーザー仮登録"""
    template_name = 'amazon/sign_up.html'
    form_class = SignUpForm
   
    def form_valid(self, form):
        """仮登録と本登録用メールの発行."""
        # 仮登録と本登録の切り替えは、is_active属性を使うと簡単です。
        # 退会処理も、is_activeをFalseにするだけにしておくと捗ります。
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        # アクティベーションURLの送付
        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': self.request.scheme,
            'domain': domain,
            'token': dumps(user.pk),
            'user': user,
        }

        subject_template = get_template('amazon/mail_template/sign_up/subject.txt')
        subject = subject_template.render(context)

        message_template = get_template('amazon/mail_template/sign_up/message.txt')
        message = message_template.render(context)

        user.email_user(subject, message)
        messages.success(self.request, '本登録用リンクを送付しました')
        return  HttpResponseRedirect(reverse('amazon:sign_up'))


class SignUpDone(generic.TemplateView):

    template_name = 'amazon/sign_up_done.html'
    timeout_seconds = getattr(settings, 'ACTIVATION_TIMEOUT_SECONDS', 60*60*24)

    def get(self, request, **kwargs):
        token = kwargs.get('token')
        try:
            user_pk = loads(token, max_age=self.timeout_seconds)

        # 期限切れ
        except SignatureExpired:
            return HttpResponseBadRequest()

        # tokenが間違っている
        except BadSignature:
            return HttpResponseBadRequest()

        # tokenは問題なし
        else:
            try:
                user = User.objects.get(pk=user_pk)
            except User.DoesNotExist:
                return HttpResponseBadRequest()
            else:
                if not user.is_active:
                    # 問題なければ本登録とする
                    user.is_active = True
                    user.save()

                    return super().get(request, **kwargs)

        return HttpResponseBadRequest()

templates/amazon/base.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">
    
    <link href="{% static 'css/base.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet" media="only screen and (max-width: 1200px)" />
    <script src="{% static 'js/script.js' %}" type="text/javascript"></script>

    <title>techpit amazon</title>
    <body>
        <header class="section-header">
            <section class="header-main">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-md-3">
                        <a href="{% url 'amazon:lp' %}">
                            <div class="brand-wrap">
                                <img class="logo" src="{% static 'images/logo-dark.png' %}">
                                <h2 class="logo-text">Techpit amazon</h2>
                            </div> <!-- brand-wrap.// -->
                        </a>
                        </div>
                        <div class="col-lg-6 col-sm-6">
                            <form method= "get" action="{% url 'amazon:item_list' %}" class="search-wrap">
                                <!-- フォームのaction属性変更 ここまで -->
    
                                    <div class="input-group">
                                        <input name="q" type="text" class="form-control" placeholder="Search">
                                        <div class="input-group-append">
                                            <button id="id_search_button" class="btn btn-warning" type="submit">
                                            <i class="fa fa-search"></i>
                                            </button>
                                    </div>
                                </div>
                            </form> <!-- search-wrap .end// -->
                        </div> <!-- col.// -->
                        <div class="col-lg-3 col-sm-6">
                            <div class="widgets-wrap d-flex justify-content-end">
                                
                                <div class="widget-header icontext">
                                    <div class="icon-wrap icon-sm bg2 round text-secondary"><i class="fa fa-user"></i></div>
                                    <div class="text-wrap">
                                        {% if user.is_authenticated %}
                                        <small>{{user.name}}さん</small>
                                        <span><a href="{% url 'amazon:logout' %}">Logout</a></span>
                                        {% else %}
                                        <small>ゲスト</small>
                                        <span><a href="{% url 'amazon:login' %}">Login</a></span>
                                        {% endif %}
                                    </div>
                                </div>	<!-- widgets-wrap.// -->	
                        </div> <!-- col.// -->
                    </div> <!-- row.// -->
                </div> <!-- container.// -->
            </section> <!-- header-main .// -->
        </header> <!-- section-header.// -->
        <div class="container" style="padding: 2rem">
                {% block content %}{% endblock %}
        </div>
        <footer class="section-footer bg2">
            <div class="container">
                <section class="footer-bottom row">
                    
                    <div class="col-sm-12">
                        <p class="text-sm-right">
        Copyright © 2019 
        <a href="#">Techpit</a>
                        </p>
                    </div>
                </section> <!-- //footer-top -->
            </div><!-- //container -->
        </footer>
        
         {% block scripts %}{% endblock %}
    </body>
</html>

templates/amazon/item_detail.html
{% extends "amazon/base.html" %}
{% block content %}
{% load static %}

<main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">
        <div class="row wow fadeIn">
            <div class="col-md-6 mb-4">
                <img src="{{ object.thumbnail.url }}" class="img-fluid" alt="">
            </div>
            <div class="col-md-6 mb-4">
                <div class="p-4">
                    <div class="mb-3">
                        <a href="">
                        <span class="badge purple mr-1">Category 2</span>
                        </a>
                        <a href="">
                        <span class="badge blue mr-1">New</span>
                        </a>
                        <a href="">
                        <span class="badge red mr-1">Bestseller</span>
                        </a>
                    </div>
                    <p class="lead">
                        <h2>{{ object.name }}</h2>
                        <span>¥{{ object.price }}</span>
                    </p>
                    <p class="lead font-weight-bold">商品説明</p>
                    <p>{{ object.description }}</p>
                </div>
            </div>
        </div>
        <hr>
        <div class="row d-flex justify-content-center wow fadeIn">

            <div class="col-md-6 text-center">

                <h4 class="my-4 h4">Additional information</h4>

                <p>
                    Djangoのようなフレームワークを利用しても、ページのデザインを綺麗にすることはできません。
                    恐らくこの教材で学習している方のほとんどがどちらかというとサーバサイドを勉強している方が多いのかと思慮しますので、
                    htmlやcssの部分はあまり得意でないという方が多いと思います。そのような方はぜひBootstrap等のCSSフレームワークを利用することをお勧めします。
                    また、コードのスニペットをネット上から拝借するのも非常に良いと思います。日本の
                    サイトですとまだこのスニペットのまとめサイトのようなものは少ないですが、海外ですと無数に存在するので、ぜひそれらを活用していただくことをお勧めします。(無料で公開されていることろが多いです)
                    特にログイン画面やサインアップ部分は「bootstrap login snippet」等で検索するといろいろな方が作成したスニペットが出てくるので、是非今後「自分でサービス開発したい！」となった際にご参考にしていただければと思います。
                </p>
            </div>
        </div>
        <div class="row wow fadeIn">
            <div class="col-lg-4 col-md-12 mb-4">
                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

            </div>
            <div class="col-lg-4 col-md-6 mb-4">
                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">
            </div>
            <div class="col-lg-4 col-md-6 mb-4">
                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

            </div>
        </div>
    </div>
</main>   
{% endblock %}

templates/amazon/item_list.html
{% extends "amazon/base.html" %}
{% block content %}
{% load static %}
    <div class="row-sm">
    {% for object in object_list %}
        
        <div class="col-md-3">
            <figure class="card card-product">
                <div class="img-wrap"> <img src="{{ object.thumbnail.url }}"></div>
                    <figcaption class="info-wrap">
                        <h6 class="title "><a href="{% url 'amazon:item_detail' object.pk %}">{{ object.name }}</a></h6>
                        
                        <div class="price-wrap">
                            <span class="price-new">{{ object.price }}円</span>
                        </div> <!-- price-wrap.// -->
                    
                    </figcaption>
            </figure> <!-- card // -->
        </div> <!-- col // -->
        
    {% endfor %}
    </div>
{% endblock %}

templates/amazon/login.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>  
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">
    <title>title here</title>
</head>
<body style="background: teal">
    <div class="container" style="padding: 2rem">
        <div class="row">
            <div class="col-md-6 offset-md-3 col-12">
                <div class="card bg-light">
                    <div class="card-body mx-auto">
                        <form action="" method="post">
                            {{ form.non_field_errors }}
                            <div class="input-group form-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-envelope"></i></span>
                                </div>
                                {{ form.username }}
                            </div>
                            {{ form.email.errors }}
        
                            <div class="input-group form-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-lock"></i></span>
                                </div>
                                {{ form.password }}
                            </div>
                            {{ form.password.error }}
                            {% csrf_token %}
                            <div class="form-group">
                                <button type="submit" name="btn" value="Login" class="btn btn-primary btn-block">Login</button>
                            </div>   
                            <p class="text-center">アカウントをお持ち出ないですか? <a href="{% url 'amazon:sign_up' %}">Sign up</a> </p>                                                            
                        </form>
                    </div> <!-- card body -->
                </div> <!-- card  -->
            </div>
        </div>
    </div>
</body>
</html>

templates/amazon/lp.html
{% extends "amazon/base.html" %}
{% block content %}
{% load static %}
    <link href="{% static 'plugins/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'plugins/owlcarousel/assets/owl.theme.default.css' %}" rel="stylesheet">
    <script src="{% static 'plugins/owlcarousel/owl.carousel.min.js' %}"></script>
  
    <section class="section-main bg padding-top-sm">
        <div class="container">
            <div class="row-sm">
                <div class="col-md-8">
                   <div class="owl-init slider-main owl-carousel" data-items="1" data-dots="false" data-nav="true">
                        {% for item in items %}
                        <div class="item-slide">
                            <img src="{{ item.thumbnail.url }}">
                        </div>
                        {% endfor %}
                        <div class="item-slide rounded">
                            <img src="{% static 'images/banners/slide2.jpg' %}">
                        </div>
                        <div class="item-slide rounded">
                            <img src="{% static 'images/banners/slide3.jpg' %}">
                        </div>
                    </div>
                </div> <!-- col.// -->
                <aside class="col-md-4">
                    <div class="card mb-3">
                        <figure class="itemside">
                            <div class="aside"><div class="img-wrap p-2 border-right"><img class="img-sm" src="{% static 'images/items/1.jpg' %}"></div></div>
                            <figcaption class="text-wrap align-self-center">
                                <h6 class="title">Group of products is here </h6>
                                <a href="#">More items</a>
                            </figcaption>
                        </figure>
                    </div> <!-- card.// -->
                    <div class="card mb-3">
                        <figure class="itemside">
                            <div class="aside"><div class="img-wrap p-2 border-right"><img class="img-sm" src="{% static 'images/items/2.jpg' %}"></div></div>
                            <figcaption class="text-wrap align-self-center">
                                <h6 class="title">Group of products  is here </h6>
                                <a href="#">More items</a>
                            </figcaption>
                        </figure>
                    </div> <!-- card.// -->
                    
                    <div class="card">
                        <figure class="itemside">
                            <div class="aside"><div class="img-wrap p-2 border-right"><img class="img-sm" src="{% static 'images/items/3.jpg' %}"></div></div>
                            <figcaption class="text-wrap align-self-center">
                                <h6 class="title">Group of products is here </h6>
                                <a href="#">More items</a>
                            </figcaption>
                        </figure>
                    </div> <!-- card.// -->
                </aside>
            </div>
        </div> <!-- container .//  -->
    </section>
    <section class="section-content padding-y bg">
        <div class="container">
        
            <div class="card">
                <div class="card-body">
            
                    <header class="section-heading">
                        <h3 class="title-section">Django Amazon</h3>
                    </header>
                    
                    <article>
                        <p>
                            この教材ではDjangoを用いてAmazonに代表されるECサイトを作成します。Djangoが提供する多くの機能の中でも、主にCBV（クラスベースビュー）を
                            積極的に用いて、書くコードの量をなるべく減らすような設計にしております。Djangoを利用すると言っても同じ機能を実現させるさせるために様々な手段がありますので、
                            この教材が紹介しているやり方が正解だとは思わず、選択肢の一つとして受け入れていただければと思います。
                            人のやり方やコードをうまく取り入れる（パクる）ことが、実務をこなせるレベルになる最短ルートだと私は考えておりますので、
                            是非ここで学んだ実装方法を積極的に活用いただけると嬉しいです。
                        </p> 
                    </article>
                </div>
            </div>
        
        </div> <!-- container .//  -->
    </section>
{% endblock %}
<!-- [2-5] ベーステンプレート読み込み追加　ここまで -->

templates/amazon/shopping_cart.html
{% extends "amazon/base.html" %}
{% block content %}
{% load static %}

{% if object.cart_items.all %}
 <div class="card shopping-cart">
    <div class="card-body">
        {% for cart_item in object.cart_items.all %}
        <div class="row">
            <div class="col-12 col-sm-12 col-md-2 text-center">
                    <img class="img-responsive" src="{{ cart_item.product.thumbnail.url }}" alt="prewiew" width="120" height="80">
            </div>
            <div class="col-12 text-sm-center col-sm-12 text-md-left col-md-6">
                <h4 class="product-name"><strong>{{ cart_item.product.name }}</strong></h4>
                <h4>
                    <small>{{ cart_item.product.description }}</small>
                </h4>
            </div> <!-- col -->
            <div class="col-12 col-sm-12 text-sm-center col-md-4 text-md-right row">
                <div class="col-3 col-sm-3 col-md-6 text-md-right" style="padding-top: 5px">
                    <h6><strong>{{ cart_item.product.price }} <span class="text-muted">x</span></strong></h6>
                </div>
                <div class="col-4 col-sm-4 col-md-4">
                    <div class="quantity">
                        <input name="amount" pk="{{ cart_item.pk }}" type="number" class="form-control" step="1" max="99" min="1" title="Qty" class="qty" size="4" value="{{ cart_item.amount }}"> 
                    </div>
                </div>
                <div class="col-2 col-sm-2 col-md-2 text-right">
                    <button name="delete" pk="{{ cart_item.pk }}" type="button" class="btn btn-outline-danger btn-xs">
                        <i class="fa fa-trash" aria-hidden="true"></i>
                    </button>
                </div>
            </div> <!-- col -->
        </div> <!-- row -->
        {% endfor %}
        <hr>
    </div> <!-- card body -->
    <div class="card-footer">
        <a href="" class="btn btn-success pull-right">Checkout</a>
        <div class="float-right">Total price: <b> ¥{{ object.total_price }}</b></div>
    </div>
    </div> <!-- card footer -->
</div> <!-- card -->
{% else %}
<p>カートが空です</p>
{% endif %}
{% endblock %}

<!-- [7-5] Ajaxリクエスト部分追加 ここから -->
{% block scripts %}
<script>
    function call_update_amount(_pk, _amount) {
        return $.ajax({
            url: '{% url "amazon:update_cart_item_amount" %}',
            type: 'POST',
            dataType: 'json',
            data: {
                cart_item_pk: _pk,
                amount: _amount
            }
        });
    }
    function call_delete_item(_pk) {
        return $.ajax({
            url: '{% url "amazon:delete_cart_item" %}',
            type: 'POST',
            dataType: 'json',
            data: {
                cart_item_pk: _pk
            }
        });
    }

    $(function() {
        var $input_amount = $('input[name="amount"]');
        var $delete_button = $('button[name="delete"]');
        $input_amount.on('change', function() {
            var cart_item_pk = $(this).attr('pk');
            var new_amount = parseInt($(this).val());
            call_update_amount(cart_item_pk, new_amount)
            .done((data) => {
                if (data.success) {
                    location.reload();
                    return;
                }
                alert(data.error);
            })
            .fail((ata, textStatus, xhr) => {
                alert(xhr);
            });
        });
        $delete_button.on('click', function() {
            var cart_item_pk = $(this).attr('pk');
            call_delete_item(cart_item_pk)
            .done((data) => {
                if (data.success) {
                    location.reload();
                    return;
                }
                alert(data.error);
            })
            .fail((ata, textStatus, xhr) => {
                alert(xhr);
            });
        });
    })
</script>
{% endblock %}
<!-- [7-5] Ajaxリクエスト部分追加 ここまで -->

templates/amazon/sign_up.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" >
    <title>title here</title>

</head>
<body style="background: #81D8D0">
    <div class="container" style="padding: 2rem">
        <div class="row">
            <div class="col-md-6 offset-md-3 col-12">
                <div class="card bg-light">
                    <div class="card-body mx-auto">
                        <form method="POST" action="">
                            {{ form.non_field_errors }}
                            <ul class="messages">
                            {% for message in messages %}
                                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                            {% endfor %}
                            </ul>
                            {% csrf_token %}
                            <div class="form-group input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"> <i class="fa fa-envelope"></i> </span>
                                    </div>
                                    {{ form.email }}
                                    
                            </div> <!-- form-group// -->
                            {{ form.email.errors }}
                            <div class="form-group input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"> <i class="fa fa-user"></i> </span>
                                    </div>
                                    {{ form.name }}
                            </div> <!-- form-group// -->
                            {{ form.name.errors }}
                            <div class="form-group input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
                                </div>
                                {{ form.password1 }}
                                
                            </div> <!-- form-group// -->
                            {{ form.password1.errors }}
                            <div class="form-group input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
                                </div>
                                {{ form.password2 }}
                                
                            </div> <!-- form-group// -->                                      
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary btn-block"> Create Account  </button>
                            </div> <!-- form-group// -->   
                            {{ form.password2.errors }}   
                            <p class="text-center">アカウントをお持ちですか? <a href="{% url 'amazon:login' %}">Log In</a> </p>                                                                 
                        </form>
                    </div>
                </div> <!-- card.// -->
            </div>
        </div>
    </div> <!-- container -->
</body>

templates/amazon/sign_up_done.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" ></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">
    <title>title here</title>

</head>
<body>
        <div class="jumbotron text-xs-center">
            <h1 class="display-3">Thank You!</h1>
                <p class="lead"><strong>Enjoy shopping!</strong> </p>
            <hr>
            <a class="btn btn-success" href="{% url 'amazon:login' %}">login</a>
        </div>
            
</body>
</html>